In [9]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.decomposition import PCA

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split

In [10]:
# MODIFYING DATA

data = pd.read_csv('carbon_nanotubes.csv', sep=';')

cols = data.columns

for col in cols[2:]:
    data[col] = data[col].str.replace(',', '.')
    data[col] = data[col].astype(float)
    
X = data.iloc[:, :5]
Y = data.iloc[:, 5:]

pca = PCA(n_components=2)
pca.fit(X) 

PCA_X = pca.transform(X)
PCA_X

array([[ 6.21606245, -2.36266666],
       [ 6.21604799, -2.36275527],
       [ 6.21603942, -2.36270964],
       ...,
       [-3.76325628,  2.67825267],
       [-3.76326204,  2.67820464],
       [-3.76325952,  2.67819741]])

In [11]:
train_X, test_X, train_Y, test_Y = train_test_split(PCA_X, Y, test_size=0.25)

reg = LinearRegression().fit(train_X, train_Y)

print('Parameters: \n{}\n'.format(reg.coef_.transpose()))
print('Intercept: \n{}\n'.format(reg.intercept_.transpose()))

# print reg.coef_.transpose().round()

predicted_values = reg.predict(test_X)
# print('Predictions: \n{}\n'.format(reg.predict(test_X)))

Parameters: 
[[ 0.00061534  0.00021481  0.00136288]
 [-0.00056025  0.00206902 -0.00065897]]

Intercept: 
[0.49901491 0.4987691  0.5022    ]



In [12]:
'''
    Model Evaluation Metrics for Regression
'''

from sklearn import metrics

# MAE
print('MAE: \n{}\n'.format(metrics.mean_absolute_error(test_Y, predicted_values)))

# MSE
print('MSE: \n{}\n'.format(metrics.mean_squared_error(test_Y, predicted_values)))

# RMSE
print('RMSE: \n{}\n'.format(np.sqrt(metrics.mean_squared_error(test_Y, predicted_values))))

# SCORE
print('Score (R^2): \n{}\n'.format(reg.score(test_X, test_Y)))

print('r2 Score: \n{}\n'.format(metrics.r2_score(test_Y, predicted_values)))

MAE: 
0.25704066616295723

MSE: 
0.08395982314604102

RMSE: 
0.28975821497593646

Score (R^2): 
-0.0012211434900093402

r2 Score: 
-0.001224437105553866

